# Generated by Django 4.0.3 on 2022-04-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=models.SlugField(default='slug', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
